name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Playwright browsers (if Playwright is used)
      run: |
        # Install system dependencies and Playwright browsers to ensure tests using Playwright run on CI
        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 \
          libxdamage1 libxfixes3 libgbm1 libasound2 libpangocairo-1.0-0 libxss1 libxcb1 \
          fonts-liberation wget ca-certificates && sudo rm -rf /var/lib/apt/lists/*
        python -m pip install playwright || true
        python -m playwright install --with-deps || true
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
  pytest

  playwright-tests:
    name: Playwright tests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest playwright
    - name: Install Playwright browsers and dependencies
      run: |
        # Install system dependencies required by Playwright on Ubuntu
        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 \
          libxdamage1 libxfixes3 libgbm1 libasound2 libpangocairo-1.0-0 libxss1 libxcb1 \
          fonts-liberation wget ca-certificates && sudo rm -rf /var/lib/apt/lists/*
        python -m playwright install --with-deps
    - name: Run Playwright/integration tests
      run: |
        # Run tests that are likely to use Playwright. Adjust the -k filter as needed.
        pytest -k "playwright or integration or terapee" -q
